Fix(dns) : fix load && use explorer-api cache
massalabs/massa-name-service pull request #11
Opened 2024-06-27 16:04 UTC by modship

2024-06-27 17:12 UTC, Thykof requested changes

2024-06-27 17:12 UTC, Thykof commented on frontend/src/utils/write-mns-sc.tsx
> +    // let map_list_asked: Map<string, number> = new Map();
```suggestion
```

2024-06-27 17:12 UTC, Thykof commented on frontend/package.json
>      "@massalabs/wallet-provider": "^2.0.1-dev.20240423112601",
```suggestion
    "@massalabs/react-ui-kit": "^0.0.5-dev",
    "@massalabs/wallet-provider": "^2.0.1-dev",
```

then run npm i to update lock file

2024-06-27 17:12 UTC, Thykof commented on frontend/src/utils/write-mns-sc.tsx
> +  const explorer_api = new ExplorerApiClient();
variable name must be camelCase

2024-06-28 12:31 UTC, Leo-Besancon approved these changes

2024-06-28 13:27 UTC, merged